In [1]:
# Get also a normally distributed random sample:
from scipy.stats import norm
import numpy as np

# Get random samples
n = 40

# Get random numbers, normally distributed, centered at 100, std=15
A = norm.rvs(size=n,loc=120,scale=14)
A = np.sort(A)
A = A.reshape((n,1))


# Get random numbers, normally distributed, centered at 95, std=10
B = norm.rvs(size=n,loc=100,scale=10)
B = np.sort(B)
B = B.reshape((n,1))

# Get random number, normally distributed, centered at 90, std=5
C = norm.rvs(size=n,loc=90,scale=5)
C = np.sort(C)
C = C.reshape((n,1))

In [2]:
AA = np.concatenate((A,B,C),axis=1)
AA

array([[  79.25035827,   73.74944208,   82.70966967],
       [  96.5970343 ,   82.23370604,   82.86724916],
       [  97.39166216,   83.17899447,   83.07318179],
       [  97.43791655,   87.44000465,   83.49868453],
       [  99.58207272,   87.63785202,   83.63906165],
       [ 106.97355578,   87.79863381,   85.97286202],
       [ 108.75584059,   90.42557687,   86.38856473],
       [ 109.856949  ,   91.36456269,   86.53321132],
       [ 110.30703652,   92.28422807,   86.75230219],
       [ 111.01532398,   92.85938741,   87.69068256],
       [ 111.35454836,   94.47387094,   88.66804422],
       [ 111.53076263,   96.10701167,   88.83223199],
       [ 111.6800262 ,   98.59549476,   89.24236428],
       [ 112.86789198,   98.59808249,   89.55134718],
       [ 113.74563857,   98.66844868,   89.57860799],
       [ 114.26325981,   99.25720162,   89.97687003],
       [ 115.11879376,  100.41914515,   90.19306427],
       [ 115.26917562,  100.94536113,   90.54432107],
       [ 115.59924695,  101.08052992,   90.84450337],
       [ 120.39320759,  101.38996534,   90.96928574],
       [ 121.94855088,  101.53572685,   91.00090002],
       [ 122.53031984,  102.41818424,   91.49792242],
       [ 123.14847064,  102.80926385,   92.18691895],
       [ 123.56931379,  103.11923976,   92.1880705 ],
       [ 123.66045323,  103.25916951,   92.3044002 ],
       [ 126.88581156,  104.44097366,   92.38339182],
       [ 128.496115  ,  104.63964743,   92.38757196],
       [ 130.49997063,  104.75782314,   92.65737514],
       [ 133.32396248,  104.87786801,   92.76337923],
       [ 134.0654564 ,  105.66351273,   93.083422  ],
       [ 135.38223049,  106.5961872 ,   93.0946677 ],
       [ 136.92701098,  106.86583022,   93.80509075],
       [ 137.45211789,  107.69577083,   94.27142447],
       [ 139.56674952,  108.59005902,   94.43436822],
       [ 140.68327592,  112.47506591,   95.5630266 ],
       [ 142.11623833,  113.28184555,   96.58803169],
       [ 142.47507654,  113.45900683,   96.62300525],
       [ 147.62570844,  115.51885565,   96.66574462],
       [ 148.4489089 ,  116.37142415,   96.68689102],
       [ 151.48005958,  120.5295426 ,   97.19535646]])

In [3]:
import pandas as pd
df = pd.DataFrame.from_dict(AA)

In [4]:
df.columns=['BG 1', 'BG 2','BG 3']
df.index.name='Person ID'
df

                 BG 1        BG 2       BG 3
Person ID
0           79.250358   73.749442  82.709670
1           96.597034   82.233706  82.867249
2           97.391662   83.178994  83.073182
3           97.437917   87.440005  83.498685
4           99.582073   87.637852  83.639062
5          106.973556   87.798634  85.972862
6          108.755841   90.425577  86.388565
7          109.856949   91.364563  86.533211
8          110.307037   92.284228  86.752302
9          111.015324   92.859387  87.690683
10         111.354548   94.473871  88.668044
11         111.530763   96.107012  88.832232
12         111.680026   98.595495  89.242364
13         112.867892   98.598082  89.551347
14         113.745639   98.668449  89.578608
15         114.263260   99.257202  89.976870
16         115.118794  100.419145  90.193064
17         115.269176  100.945361  90.544321
18         115.599247  101.080530  90.844503
19         120.393208  101.389965  90.969286
20         121.948551  101.535727  91.000900
21         122.530320  102.418184  91.497922
22         123.148471  102.809264  92.186919
23         123.569314  103.119240  92.188070
24         123.660453  103.259170  92.304400
25         126.885812  104.440974  92.383392
26         128.496115  104.639647  92.387572
27         130.499971  104.757823  92.657375
28         133.323962  104.877868  92.763379
29         134.065456  105.663513  93.083422
30         135.382230  106.596187  93.094668
31         136.927011  106.865830  93.805091
32         137.452118  107.695771  94.271424
33         139.566750  108.590059  94.434368
34         140.683276  112.475066  95.563027
35         142.116238  113.281846  96.588032
36         142.475077  113.459007  96.623005
37         147.625708  115.518856  96.665745
38         148.448909  116.371424  96.686891
39         151.480060  120.529543  97.195356

In [5]:
df.to_csv('BG-db.csv')